In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
bios = pd.read_csv('Pandas/datasets/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

## Is the dataset biased toward certain regions or eras?

In [5]:
by_country = bios['born_country'].value_counts()
by_country

born_country
USA        9641
GER        6891
GBR        5792
FRA        5143
ITA        4709
           ...
GIB           1
NFI           1
Munich        1
Altmark       1
Aarhus        1
Name: count, Length: 236, dtype: int64

In [6]:
bios['born_datetime'] = pd.to_datetime(bios['born_date'])
bios['born_year'] = bios['born_datetime'].dt.year
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0

In [15]:
by_born_year = bios['born_year'].value_counts()

In [16]:
by_born_year.sort_index()

born_year
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: count, Length: 177, dtype: int64

- yes the dataset has majority entries of nations like USA, Germany, Great Britain.

- Simulatneously, this dataset has very few entries for Countries like: India, Munich etc.

- Also the early era athletes, have got less exposure

## How does missing data affect conclusions about early-era athletes?

- it introduces an uncertainty

- early era athletes have more missing values specific to physical attributee: height, weight.

- It Impacts overall averages in comparitive analysis of modern and early era athletes

- Also, interpretation becomes difficult about correlation b/w physical attributes and longetivity

## Why might height/weight data be missing more often historically?

- Due to older appraoch of keeping records: absolutely manual and handwritten

- modern athletes are favoured by robust system of data collection, maintainance due to tech innovations.

## What conclusions can/cannot be drawn reliably from this dataset?

> can

- Trends in data availability
- Absolute analysis for modern era athletes


> can't

- Comparative analysis b/w early and modern era athletes
- Athletic participation levels by country